[tool.poetry]
name = "mt4-trader-vps-setup"
version = "0.1.0"
description = ""
authors = ["Sébastien Eustace <sebastien@eustace.io>"]

[tool.poetry.dependencies]
python = "*"
wget = "^3.2"

[tool.poetry.dev-dependencies]
pytest = "^3.6"